version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:3005:3005"
    volumes:
      - ".node_modules/app/node_modules"
      - "/app/node_modules"
      - ".:/app"
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:3006:3006"
    volumes:
      - ".node_modules/app/node_modules"
      - "/app/node_modules"
      - "./server:/app"
  redis-server:
    image: "redis"
    sysctls:
      - net.core.somaxconn=511
