version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "0.0.0.0:3002:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"
